apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: pingdatavolume
          persistentVolumeClaim:
            claimName: claimtopingdata
      containers:
        - name: pingpong
          image: vilkorppi/pingpong:v2
          volumeMounts:
          - name: pingdatavolume
            mountPath: /usr/src/pingpong/howmanypings
