apiVersion: v1
kind: Service
metadata:
  name: stringgeneratorservice
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: stringgenerator
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3012