apiVersion: batch/v1
kind: CronJob
metadata:
  name: todostoday
  namespace: exercises
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: joboftoday
            image: job:v1
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
