apiVersion: apps/v1
kind: Deployment
metadata:
  name: stringrandom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stringrandom
  template:
    metadata:
      labels:
        app: stringrandom
    spec:
      containers:
        - name: cookiemonster
          image: vilkorppi/generator:v2
