apiVersion: v1
kind: Service
metadata:
  name: pingpongservice
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - port: 567
      protocol: TCP
      targetPort: 3011