apiVersion: v1
kind: Service
metadata:
  name: webserverportService
spec:
  type: NodePort
  selector:
    app: webserverport
  ports:
    - name: http
      nodePort: 30050
      protocol: TCP
      port: 456
      targetPort: 3007